export { Home } from './Home';
export { FullPost } from './FullPost';
export { AddPost } from './AddPost';
export { Registration } from './Registration';
export { Login } from './Login';
export { TagPage } from './TagPage';
export { GenrePage } from './GenrePage';
export { EditActor } from './EditActor';
export { ActorsList } from './ActorsList';
